### ISSUE TITLE
[BUG] explicit-return-type failed to function when using styled-component

### ISSUE THREAD

**Issue by heikezy** [makeflow/magicspace#16]
## Description

Several tsx codes with relatively heavily-used styled-component are disregarded by tslint. 

More specifically, when `${props => props.theme.text.navPlaceholder}` is shown in the style, the part of linter that handles `explicit-return-type` anaylizing seems to break down, and tends to ignore return-type implicity all the way down to the end of the file.

## Codes To Reproduce

One sample among a few that could lead to the described abnormal behavior of lint are provided as follows:

```typescript
import classNames from 'classnames';
import React, {Component} from 'react';
import {RouteComponentProps} from 'react-router';
import {NavLink, withRouter} from 'react-router-dom';

import {styled} from 'theme';
import {observer} from 'utils/mobx';

const Wrapper = styled.div`
  ul {
    li {
      list-style-type: none;
      float: left;
    }
  }
`;

const HeaderNavLink = styled(NavLink)`
  display: inline-block;
  text-decoration: none;
  color: ${props => props.theme.text.navPlaceholder};
  font-size: 16px;
  padding: 0 20px;

  &:hover {
    color: ${props => props.theme.text.navPrimary};
  }

  &.active {
    color: ${props => props.theme.text.navPrimary};
    text-decoration: none;

    &::after {
      top: -10px;
      content: '';
      margin-left: auto;
      margin-right: auto;
      position: relative;
      display: block;
      width: 20px;
      height: 4px;
      background-color: ${props => props.theme.accent()};
    }
  }
`;

export interface HeaderNavProps extends RouteComponentProps<any> {
  className?: string;
}

@observer
export class HeaderNav extends Component<HeaderNavProps> {
  render() {
    let {className} = this.props;

    return (
      <Wrapper className={classNames('header-nav', className)}>
        <ul>
          <li>
            <HeaderNavLink to="/convention">规范</HeaderNavLink>
          </li>
          <li>
            <HeaderNavLink to="/qa">问答</HeaderNavLink>
          </li>
        </ul>
      </Wrapper>
    );
  }

  test() {
    return "reachable return statement";
  } 

  static Wrapper = Wrapper;
}

export const HeaderNavWithRouter = withRouter(HeaderNav);

```

**Comment by heikezy** [comment]
## Related Building Error

This stops react-app-rewired from building the project. From the error information given, I'd assume this is exactly the cause of the issue.

```
The 'explicit-return-type' rule threw an error in 'D:/Projects/Bus/Makeflow/librarian/client/src/components/home/header/@header-nav.tsx':
TypeError: Cannot read property 'getEnd' of undefined
    at ExplicitReturnTypeWalker.buildFixer (D:\Projects\Bus\Makeflow\librarian\node_modules\@magicspace\tslint-rules\bld\rules\explicitReturnTypeRule.js:93:112)
    at callback (D:\Projects\Bus\Makeflow\librarian\node_modules\@magicspace\tslint-rules\bld\rules\explicitReturnTypeRule.js:60:37)
    at visitNode (D:\Projects\Bus\Makeflow\librarian\node_modules\typescript\lib\typescript.js:14800:24)
    at Object.forEachChild (D:\Projects\Bus\Makeflow\librarian\node_modules\typescript\lib\typescript.js:15171:24)
    at callback (D:\Projects\Bus\Makeflow\librarian\node_modules\@magicspace\tslint-rules\bld\rules\explicitReturnTypeRule.js:64:26)
    at visitNodes (D:\Projects\Bus\Makeflow\librarian\node_modules\typescript\lib\typescript.js:14809:30)
    at Object.forEachChild (D:\Projects\Bus\Makeflow\librarian\node_modules\typescript\lib\typescript.js:15169:56)
    at callback (D:\Projects\Bus\Makeflow\librarian\node_modules\@magicspace\tslint-rules\bld\rules\explicitReturnTypeRule.js:64:26)
    at visitNode (D:\Projects\Bus\Makeflow\librarian\node_modules\typescript\lib\typescript.js:14800:24)
    at Object.forEachChild (D:\Projects\Bus\Makeflow\librarian\node_modules\typescript\lib\typescript.js:14991:21)
```

**Comment by vilic** [comment]
其实这个 bug 应该算是 https://github.com/makeflow/magicspace/commit/d4335e7a26beb61ad377f3eeab7c80a9037d37f2 修的
